services:
  - type: web
    name: lavka26-bot
    env: node
    plan: free
    rootDir: ./bot
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    healthCheckGracePeriod: 60
    healthCheckInterval: 60
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8500920411:AAH_lBSuXMpkDLDMs6IRpLhrTe0G9JTaKmg
      - key: TELEGRAM_WEBHOOK_URL
        value: https://lavka26-bot.onrender.com
      - key: VERCEL_API_URL
        value: https://lavka26.vercel.app/api
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: NODE_ENV
        value: production
